### ISSUE TITLE
TODO para la funcionalidad en los pagos 

### ISSUE THREAD

**Issue by Matiaseze** [UNPSJB/TallerChaPin#67]
- [x] -Control para que el monto no supere la cantidad ingresada

- [x] -Mostrar el monto total en el modal y un saldo restante
- [x] -Probar si anda el VIP del cliente y no permitirle retirar otro vehículo si tiene una factura restante (en caso de haber retirado el anterior)
